file:
  upload-dir-shoes: C:/temp/imageShoes/
  upload-dir-avatar: C:/temp/imageUser/
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    format:
      date-time: dd/MM/yyyy HH:mm:ss a
      date: dd/MM/yyyy
  datasource:
    #url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://localhost:3306/shoes?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123abc
    initialization-mode: always
  #  tomcat:
  #    max-wait: 20000
  #    max-active: 50
  #    max-idle: 20
  #    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        show-sql: true
          #format_sql: true
          # id:
        # new_generator_mappings: false

server:
  port: 8080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 43200000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
Duser:
  timezone: Asia/Ho Chi Minh
